### ISSUE TITLE
关于一个业务查询

### ISSUE THREAD

**Issue by cw592501314** [interview4php/ExaminationQ#6]
1,订单表记录了下单时间为时间戳,然后我现在要查询当前时间一天内的订单,判断是查询下单时间>当前时间减1天的时间戳,   因为订单时间是按时间插入,所以下单时间数据的排序都是从大到小.
问题:怎么做才能让当SQL查询到条件不成立就马上不继续查询下去,而不是全部记录扫描一遍.??

**Comment by yoooong** [comment]
select column  from order  where to_days(column_time) = to_days(now());

**Comment by cw592501314** [comment]
又学习到了一个新知识,但是这样还是会把所有的订单行数据查询并且判断一次吧?

**Comment by cw592501314** [comment]
另外勇哥有做个定时方面的业务吗?比如三天如果不接收红包就自动返回的功能,
我的思路:crontab定时两个任务,1.每天执行一次数据表扫描  红包:未接收 的记录且 时间在大于2天小于3天的范围,把记录存放在redis里面.
2.每天每分钟执行一次定时,将任务1中的redis数据判断是否在当前时间一分钟内.如果在就去查询数据库查看红包接收状态,如果还是未接收,就执行返回红包操作,
问题:数据量大的时候,会不会有数据库压力,2,redis最小为1分钟,有误差.应该注意哪些?

**Comment by yoooong** [comment]
@cw592501314  会，设计不合理。一般发给用户的红包，用户不接收，就当自动作废，接收了就记录下来。
